create table if not exists public.milk_entry_audit (
  id bigint generated by default as identity primary key,
  milk_entry_id bigint not null,
  cooperative_id uuid not null,
  user_id uuid not null,
  changed_by uuid,
  old_liters numeric,
  new_liters numeric,
  old_shift text,
  new_shift text,
  old_notes text,
  new_notes text,
  changed_at timestamptz not null default now()
);

alter table public.milk_entry_audit enable row level security;
revoke all on public.milk_entry_audit from anon, authenticated;

drop policy if exists "Users can update own milk entries" on public.milk_entries;
create policy "Users can update own milk entries"
on public.milk_entries for update to authenticated
using (user_id = auth.uid())
with check (user_id = auth.uid());

create or replace function public.audit_milk_entry_update()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if old.liters is distinct from new.liters
     or old.shift is distinct from new.shift
     or old.notes is distinct from new.notes then
    insert into public.milk_entry_audit (
      milk_entry_id, cooperative_id, user_id, changed_by,
      old_liters, new_liters, old_shift, new_shift, old_notes, new_notes
    ) values (
      old.id, old.cooperative_id, old.user_id, auth.uid(),
      old.liters, new.liters, old.shift, new.shift, old.notes, new.notes
    );
  end if;
  return new;
end;
$$;

drop trigger if exists milk_entry_update_audit on public.milk_entries;
create trigger milk_entry_update_audit
after update on public.milk_entries
for each row execute function public.audit_milk_entry_update();

