-- Controles operacionais do LeiteDia: fechamento, auditoria visível e backups restauráveis.

create table if not exists public.closed_periods (
  id bigint generated by default as identity primary key,
  cooperative_id uuid not null,
  start_date date not null,
  end_date date not null,
  reason text,
  closed_by uuid not null references public.profiles(id),
  closed_at timestamptz not null default now(),
  reopened_at timestamptz,
  reopened_by uuid references public.profiles(id),
  check (end_date >= start_date)
);

create index if not exists closed_periods_cooperative_dates_idx
  on public.closed_periods (cooperative_id, start_date, end_date)
  where reopened_at is null;

alter table public.closed_periods enable row level security;
grant select, insert, update on public.closed_periods to authenticated;
grant usage, select on sequence public.closed_periods_id_seq to authenticated;

drop policy if exists "Members can view cooperative closed periods" on public.closed_periods;
create policy "Members can view cooperative closed periods"
on public.closed_periods for select to authenticated
using (cooperative_id = (select cooperative_id from public.profiles where id = auth.uid()));

drop policy if exists "Admins can close periods" on public.closed_periods;
create policy "Admins can close periods"
on public.closed_periods for insert to authenticated
with check (
  cooperative_id = (select cooperative_id from public.profiles where id = auth.uid() and role = 'admin' and active = true)
  and closed_by = auth.uid()
);

drop policy if exists "Admins can reopen periods" on public.closed_periods;
create policy "Admins can reopen periods"
on public.closed_periods for update to authenticated
using (cooperative_id = (select cooperative_id from public.profiles where id = auth.uid() and role = 'admin' and active = true))
with check (cooperative_id = (select cooperative_id from public.profiles where id = auth.uid() and role = 'admin' and active = true));

create or replace function public.reject_closed_period_entry()
returns trigger language plpgsql security definer set search_path = public as $$
begin
  if current_setting('leitedia.restore', true) = 'on' then return new; end if;
  if exists (
    select 1 from public.closed_periods p
    where p.cooperative_id = new.cooperative_id
      and p.reopened_at is null
      and new.entry_date between p.start_date and p.end_date
  ) then
    raise exception 'O período deste lançamento está fechado pela cooperativa.' using errcode = 'P0001';
  end if;
  return new;
end;
$$;

drop trigger if exists milk_entry_closed_period_guard on public.milk_entries;
create trigger milk_entry_closed_period_guard
before insert or update on public.milk_entries
for each row execute function public.reject_closed_period_entry();

-- Auditoria visível apenas para o dono do lançamento ou administrador da cooperativa.
grant select on public.milk_entry_audit to authenticated;
drop policy if exists "Members can view permitted audit" on public.milk_entry_audit;
create policy "Members can view permitted audit"
on public.milk_entry_audit for select to authenticated
using (
  user_id = auth.uid()
  or cooperative_id = (
    select cooperative_id from public.profiles
    where id = auth.uid() and role = 'admin' and active = true
  )
);

create table if not exists public.data_backups (
  id uuid primary key default gen_random_uuid(),
  cooperative_id uuid not null,
  owner_user_id uuid not null references public.profiles(id),
  created_by uuid not null references public.profiles(id),
  created_at timestamptz not null default now(),
  label text,
  payload jsonb not null,
  restored_at timestamptz,
  restored_by uuid references public.profiles(id)
);

alter table public.data_backups enable row level security;
grant select on public.data_backups to authenticated;

drop policy if exists "Members can view permitted backups" on public.data_backups;
create policy "Members can view permitted backups"
on public.data_backups for select to authenticated
using (
  owner_user_id = auth.uid()
  or cooperative_id = (
    select cooperative_id from public.profiles
    where id = auth.uid() and role = 'admin' and active = true
  )
);

create or replace function public.create_data_backup(target_user_id uuid default auth.uid(), backup_label text default null)
returns jsonb language plpgsql security definer set search_path = public as $$
declare
  actor public.profiles%rowtype;
  target public.profiles%rowtype;
  backup_id uuid;
begin
  select * into actor from public.profiles where id = auth.uid() and active = true;
  select * into target from public.profiles where id = target_user_id and active = true;
  if actor.id is null or target.id is null or actor.cooperative_id <> target.cooperative_id
     or (actor.role <> 'admin' and actor.id <> target.id) then
    raise exception 'Sem permissão para criar este backup.' using errcode = '42501';
  end if;

  insert into public.data_backups(cooperative_id, owner_user_id, created_by, label, payload)
  values (target.cooperative_id, target.id, actor.id, backup_label,
    jsonb_build_object(
      'version', 1,
      'producers', coalesce((select jsonb_agg(to_jsonb(p)) from public.producers p where p.user_id = target.id), '[]'::jsonb),
      'milk_entries', coalesce((select jsonb_agg(to_jsonb(m)) from public.milk_entries m where m.user_id = target.id), '[]'::jsonb)
    )) returning id into backup_id;
  return jsonb_build_object('id', backup_id);
end;
$$;

create or replace function public.restore_data_backup(backup_id uuid)
returns jsonb language plpgsql security definer set search_path = public as $$
declare
  actor public.profiles%rowtype;
  backup public.data_backups%rowtype;
  producer_count integer := 0;
  entry_count integer := 0;
begin
  select * into actor from public.profiles where id = auth.uid() and active = true;
  select * into backup from public.data_backups where id = backup_id;
  if actor.id is null or backup.id is null or actor.cooperative_id <> backup.cooperative_id
     or (actor.role <> 'admin' and actor.id <> backup.owner_user_id) then
    raise exception 'Sem permissão para restaurar este backup.' using errcode = '42501';
  end if;

  insert into public.producers(id, cooperative_id, user_id, name, document, phone, community, active)
  select x.id, x.cooperative_id, x.user_id, x.name, x.document, x.phone, x.community, x.active
  from jsonb_to_recordset(backup.payload->'producers') as x(
    id bigint, cooperative_id uuid, user_id uuid, name text, document text, phone text, community text, active boolean
  )
  on conflict (id) do update set name=excluded.name, document=excluded.document, phone=excluded.phone,
    community=excluded.community, active=excluded.active
  where producers.user_id = backup.owner_user_id;
  get diagnostics producer_count = row_count;

  perform set_config('leitedia.restore', 'on', true);
  insert into public.milk_entries(id, cooperative_id, user_id, entry_date, entry_time, client_entry_id,
    producer_id, supplier, shift, liters, temperature, fat_percentage, notes)
  select x.id, x.cooperative_id, x.user_id, x.entry_date, x.entry_time, x.client_entry_id,
    x.producer_id, x.supplier, x.shift, x.liters, x.temperature, x.fat_percentage, x.notes
  from jsonb_to_recordset(backup.payload->'milk_entries') as x(
    id bigint, cooperative_id uuid, user_id uuid, entry_date date, entry_time time, client_entry_id uuid,
    producer_id bigint, supplier text, shift text, liters numeric, temperature numeric, fat_percentage numeric, notes text
  )
  on conflict (id) do nothing;
  get diagnostics entry_count = row_count;

  update public.data_backups set restored_at=now(), restored_by=actor.id where id=backup.id;
  return jsonb_build_object('producers_restored', producer_count, 'entries_restored', entry_count);
end;
$$;

revoke all on function public.create_data_backup(uuid,text) from public, anon;
revoke all on function public.restore_data_backup(uuid) from public, anon;
grant execute on function public.create_data_backup(uuid,text) to authenticated;
grant execute on function public.restore_data_backup(uuid) to authenticated;
