create table if not exists public.producers (
  id bigint generated by default as identity primary key,
  cooperative_id uuid not null,
  name text not null check (char_length(trim(name)) >= 3),
  document text,
  phone text,
  community text,
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists producers_cooperative_name_idx
  on public.producers (cooperative_id, name);

alter table public.producers enable row level security;

drop policy if exists "Cooperative members can view producers" on public.producers;
create policy "Cooperative members can view producers"
on public.producers for select to authenticated
using (
  cooperative_id = (
    select cooperative_id from public.profiles where id = auth.uid()
  )
);

drop policy if exists "Admins can insert producers" on public.producers;
create policy "Admins can insert producers"
on public.producers for insert to authenticated
with check (
  cooperative_id = (
    select cooperative_id from public.profiles
    where id = auth.uid() and role = 'admin' and active = true
  )
);

drop policy if exists "Admins can update producers" on public.producers;
create policy "Admins can update producers"
on public.producers for update to authenticated
using (
  cooperative_id = (
    select cooperative_id from public.profiles
    where id = auth.uid() and role = 'admin' and active = true
  )
)
with check (
  cooperative_id = (
    select cooperative_id from public.profiles
    where id = auth.uid() and role = 'admin' and active = true
  )
);

alter table public.milk_entries
  add column if not exists producer_id bigint references public.producers(id);

create index if not exists milk_entries_producer_id_idx
  on public.milk_entries (producer_id);

alter table public.milk_entries
  drop constraint if exists milk_entries_shift_check;

alter table public.milk_entries
  add constraint milk_entries_shift_check
  check (shift in ('Manhã', 'Tarde')) not valid;

grant select on public.producers to authenticated;
grant insert, update on public.producers to authenticated;
grant usage, select on sequence public.producers_id_seq to authenticated;

